name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out
        uses: actions/checkout@v2

      - name: Cache go mod
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get tag
        uses: olegtarasov/get-tag@v2
        id: tagName

      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Build amd64
        uses: izumin5210/action-go-crossbuild@v1.0.0
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          CGO_ENABLE: 0
        with:
          name: hysteria
          arch: amd64
          dest: ./dist/
          ldflags: -w -s -X main.appVersion=${{ env.GIT_TAG_NAME }} -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          os: windows,linux,darwin
          package: ./cmd

      - name: Build embedded
        uses: izumin5210/action-go-crossbuild@v1.0.0
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          name: hysteria
          arch: arm,mipsle
          dest: ./dist/
          ldflags: -w -s -X main.appVersion=${{ env.GIT_TAG_NAME }} -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          os: linux
          package: ./cmd

      - name: Upload
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: false
          allow_override: true
          files: >
            ./dist/hysteria_windows_amd64.zip
            ./dist/hysteria_linux_amd64.tar.gz
            ./dist/hysteria_darwin_amd64.zip
            ./dist/hysteria_linux_arm.tar.gz
            ./dist/hysteria_linux_mipsle.tar.gz
